# -*- coding: utf-8 -*-
"""Desertation 2026 Airline Dataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LAeeZoc_Xu3_JezVjS_gOOkBuqSiLvZn

Install and import libraries
"""

!pip install pandas scikit-learn nltk transformers datasets kaggle -q

import pandas as pd
import numpy as np
import re
import nltk
import torch
import time
from transformers import Trainer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

nltk.download('vader_lexicon')

"""Checking GPU"""

print("GPU available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))

"""Downloading, loading and inspecting the Airline Dataset from Kaggle"""

!kaggle datasets download -d crowdflower/twitter-airline-sentiment
!unzip -o twitter-airline-sentiment.zip

df = pd.read_csv("Tweets.csv")
df.head()

print("Shape of dataset:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

"""Keeping only relevant columns and checking class distribution"""

df = df[['text', 'airline_sentiment']]
df.head()

print(df['airline_sentiment'].value_counts())

"""Map sentiment labels to numbers

We will use:

negative = 0

neutral = 1

positive = 2
"""

label_map = {
    'negative': 0,
    'neutral': 1,
    'positive': 2
}

df['label'] = df['airline_sentiment'].map(label_map)
df.head()

"""Define preprocessing function and applying"""

def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)      # remove URLs
    text = re.sub(r"@\w+", "", text)         # remove mentions
    text = re.sub(r"#", "", text)            # remove hashtag sign but keep word
    text = re.sub(r"[^\w\s]", "", text)      # remove punctuation
    text = re.sub(r"\s+", " ", text).strip() # remove extra spaces
    return text

df['clean_text'] = df['text'].apply(clean_text)
df[['text', 'clean_text']].head(10)

df = df.sample(5000, random_state=42).reset_index(drop=True)

print("Dataset reduced for fair comparison:", df.shape)

"""Split dataset into train and test"""

X = df['clean_text']
y = df['label']

X_train_text, X_test_text, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Training samples:", len(X_train_text))
print("Testing samples:", len(X_test_text))

"""Model 1: VADER (Lexicon-based)"""

from nltk.sentiment.vader import SentimentIntensityAnalyzer

sia = SentimentIntensityAnalyzer()

def vader_predict(text):
    score = sia.polarity_scores(text)['compound']
    if score >= 0.05:
        return 2   # positive
    elif score <= -0.05:
        return 0   # negative
    else:
        return 1   # neutral

start_time = time.time()
y_pred_vader = X_test_text.apply(vader_predict)
vader_time = time.time() - start_time

print("VADER predictions completed.")
print("Time taken (seconds):", round(vader_time, 4))

print("VADER Accuracy:", round(accuracy_score(y_test, y_pred_vader), 4))
print("VADER Precision:", round(precision_score(y_test, y_pred_vader, average='weighted'), 4))
print("VADER Recall:", round(recall_score(y_test, y_pred_vader, average='weighted'), 4))
print("VADER F1 Score:", round(f1_score(y_test, y_pred_vader, average='weighted'), 4))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_vader, target_names=['negative', 'neutral', 'positive']))

"""Model 2: TF-IDF + Logistic Regression"""

vectorizer = TfidfVectorizer(max_features=5000)

X_train_tfidf = vectorizer.fit_transform(X_train_text)
X_test_tfidf = vectorizer.transform(X_test_text)

print("TF-IDF train shape:", X_train_tfidf.shape)
print("TF-IDF test shape:", X_test_tfidf.shape)

lr_model = LogisticRegression(max_iter=1000)

start_time = time.time()
lr_model.fit(X_train_tfidf, y_train)
lr_train_time = time.time() - start_time

print("Logistic Regression training completed.")
print("Training time (seconds):", round(lr_train_time, 4))

start_time = time.time()
y_pred_lr = lr_model.predict(X_test_tfidf)
lr_inference_time = time.time() - start_time

print("Logistic Regression predictions completed.")
print("Inference time (seconds):", round(lr_inference_time, 4))

print("Logistic Regression Accuracy:", round(accuracy_score(y_test, y_pred_lr), 4))
print("Logistic Regression Precision:", round(precision_score(y_test, y_pred_lr, average='weighted'), 4))
print("Logistic Regression Recall:", round(recall_score(y_test, y_pred_lr, average='weighted'), 4))
print("Logistic Regression F1 Score:", round(f1_score(y_test, y_pred_lr, average='weighted'), 4))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_lr, target_names=['negative', 'neutral', 'positive']))

"""Compare VADER vs Logistic Regression"""

results = pd.DataFrame({
    'Model': ['VADER', 'Logistic Regression'],
    'Accuracy': [
        accuracy_score(y_test, y_pred_vader),
        accuracy_score(y_test, y_pred_lr)
    ],
    'Precision': [
        precision_score(y_test, y_pred_vader, average='weighted'),
        precision_score(y_test, y_pred_lr, average='weighted')
    ],
    'Recall': [
        recall_score(y_test, y_pred_vader, average='weighted'),
        recall_score(y_test, y_pred_lr, average='weighted')
    ],
    'F1 Score': [
        f1_score(y_test, y_pred_vader, average='weighted'),
        f1_score(y_test, y_pred_lr, average='weighted')
    ]
})

results

"""Model 3: BERT"""

# =========================
# BERT FULL SETUP (FINAL CORRECT VERSION)
# =========================

from datasets import Dataset
from transformers import BertTokenizer, BertForSequenceClassification

# ✅ USE SAME SPLIT (DO NOT RESPLIT)
# X_train_text, X_test_text, y_train, y_test already exist

# 1. Convert to HuggingFace dataset
train_df = pd.DataFrame({
    'text': X_train_text,
    'label': y_train
})

test_df = pd.DataFrame({
    'text': X_test_text,
    'label': y_test
})

train_dataset = Dataset.from_pandas(train_df.reset_index(drop=True))
test_dataset = Dataset.from_pandas(test_df.reset_index(drop=True))

# 2. Load tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# 3. Tokenization function
def tokenize(example):
    return tokenizer(
        example['text'],
        truncation=True,
        padding='max_length',
        max_length=128
    )

# 4. Apply tokenization
train_dataset = train_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

# 5. Set PyTorch format
train_dataset.set_format(
    type='torch',
    columns=['input_ids', 'attention_mask', 'label']
)

test_dataset.set_format(
    type='torch',
    columns=['input_ids', 'attention_mask', 'label']
)

# 6. Load BERT model
model = BertForSequenceClassification.from_pretrained(
    'bert-base-uncased',
    num_labels=3
)

print("✅ BERT setup complete with SAME dataset split.")

"""Training the model"""

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir='./results',
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=2,
    logging_dir='./logs',
    report_to="none"
)

print("✅ Training arguments ready")

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset
)

trainer.train()

predictions = trainer.predict(test_dataset)

y_pred_bert = predictions.predictions.argmax(axis=1)
y_true_bert = y_test.values

print("BERT Accuracy:", accuracy_score(y_true_bert, y_pred_bert))
print("BERT Precision:", precision_score(y_true_bert, y_pred_bert, average='weighted'))
print("BERT Recall:", recall_score(y_true_bert, y_pred_bert, average='weighted'))
print("BERT F1:", f1_score(y_true_bert, y_pred_bert, average='weighted'))

print(classification_report(
    y_true_bert,
    y_pred_bert,
    target_names=['negative', 'neutral', 'positive']
))

"""Results:"""

final_results = pd.DataFrame({
    'Model': ['VADER', 'Logistic Regression', 'BERT'],
    'Accuracy': [
        accuracy_score(y_test, y_pred_vader),
        accuracy_score(y_test, y_pred_lr),
        accuracy_score(y_true_bert, y_pred_bert)
    ],
    'Precision': [
        precision_score(y_test, y_pred_vader, average='weighted'),
        precision_score(y_test, y_pred_lr, average='weighted'),
        precision_score(y_true_bert, y_pred_bert, average='weighted')
    ],
    'Recall': [
        recall_score(y_test, y_pred_vader, average='weighted'),
        recall_score(y_test, y_pred_lr, average='weighted'),
        recall_score(y_true_bert, y_pred_bert, average='weighted')
    ],
    'F1 Score': [
        f1_score(y_test, y_pred_vader, average='weighted'),
        f1_score(y_test, y_pred_lr, average='weighted'),
        f1_score(y_true_bert, y_pred_bert, average='weighted')
    ]
})

final_results

import matplotlib.pyplot as plt

# Set index for better plotting
final_results.set_index('Model', inplace=True)

final_results.plot(kind='bar')

plt.title("Model Performance Comparison")
plt.ylabel("Score")
plt.xlabel("Model")
plt.xticks(rotation=0)
plt.legend(loc='lower right')

plt.tight_layout()
plt.show()

final_results['F1 Score'].plot(kind='bar')

plt.title("F1 Score Comparison Across Models")
plt.ylabel("F1 Score")
plt.xlabel("Model")
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

from sklearn.metrics import ConfusionMatrixDisplay

# VADER
ConfusionMatrixDisplay.from_predictions(y_test, y_pred_vader)
plt.title("VADER Confusion Matrix")
plt.show()

# Logistic Regression
ConfusionMatrixDisplay.from_predictions(y_test, y_pred_lr)
plt.title("Logistic Regression Confusion Matrix")
plt.show()

# BERT
ConfusionMatrixDisplay.from_predictions(y_true_bert, y_pred_bert)
plt.title("BERT Confusion Matrix")
plt.show()